2019-4-17
Replace cower dependancy with auracle

diff --git a/aurt b/aurt
--- a/aurt
+++ b/aurt
@@ -1,14 +1,12 @@
 #!/bin/bash
-# aurt 2019-02-13   Depencencies: sudo base-devel mc expac pkgfile aurutils 1.5 cower repoctl
+# aurt 2019-04-17   Depencencies: sudo base-devel mc expac pkgfile aurutils1.5 auracle repoctl
 # date:year-mo-day
-# shellcheck disable=SC1091,SC2002
+# shellcheck disable=SC1091,SC2002,SC2034
 
 export PAGER=mc
 export AURDEST="${HOME}"/z-AUR-Aurt.git/
 pdate=$(date '+%Y-%m-%d')
 readarray -t pkglist <<< "$(echo "$@" | awk '{$1=""; print}'|fmt -1|awk '{$1=$1}1')"
-OffUds=
-LocPkgs=
 bold='\033[1m'
 cyan='\033[0;96m'
 none='\033[00m'
@@ -19,7 +17,7 @@ install () {
 
 	aursync --no-confirm "${pkglist[@]}"
 
-	sudo pacsync aur                                                   ## NEW ##
+	sudo pacsync aur
 
 	sudo pacman -S --noconfirm --color=always "${pkglist[@]}"
 
@@ -78,7 +76,6 @@ remove () {
 
 	. aurt-info --removeprint1 "${2}"
 
-
 	rm -fr "${HOME}"/z-AUR-Aurt.git/"${2}"
 
 	repoctl remove "${2}"
@@ -97,31 +94,32 @@ fi
 }
    #================================================= MANUALINSTALL ======================================================
 			### This must be ran in the directory containing the package, < *.pkg.tar* >  ###
+
 manualinstall () {
 
 PKG="$2"
-TEST=$(find -maxdepth 1 | awk -F/ '/pkg.tar/ {print $2}' | grep $2)
+TEST=$(find . -maxdepth 1 | awk -F/ '/pkg.tar/ {print $2}' | grep "${2}")
 
-if	[[ -n $(find -maxdepth 1 | grep pkg.tar.xz) ]]; then
+if	find . -maxdepth 1 | grep -q pkg.tar.xz ; then
+	PNAME=$(xzcat "${PKG}" 2>/dev/null | awk '/pkgname/ {print $3}' | awk '!seen[$0]++')
 
-NAME=$(xzcat "${PKG}" 2>/dev/null | awk '/pkgname/ {print $3}' )
     elif
-	[[ -n $(find -maxdepth 1 | grep pkg.tar) ]]; then
 
-NAME=$(cat "${PKG}" 2>/dev/null | awk '/pkgname/ {print $3}')
+	find . -maxdepth 1 | grep -q pkg.tar ; then
+	PNAME=$(awk '/pkgname/ {print $3}' "${PKG}" | awk '!seen[$0]++')
 
 fi
 
-if	[[ $PKG = $TEST ]]; then
+if	[[ $PKG = "$TEST" ]]; then
 	cp "${PKG}" /var/cache/pacman/aur
 	echo ":: Copying $2 to local aur repo"
     else
-	echo ":: Error: "$2" is not present"; exit
+	echo ":: Error: ${2} is not present"; exit
 fi
 	repoctl add "${PKG}"
 	repoctl update
 	sudo pacsync aur &>/dev/null
-	sudo pacman -S "${NAME}"
+	sudo pacman -S "${PNAME}"
 }
    #=================================================== UDREPORT ========================================================
 
@@ -154,19 +152,13 @@ udreport () {
 	. aurt-info --udreportprint2
 }
    #================================================== SYNC TESTING =====================================================
-   ### parallelize via grouping and { backgrounding commands ; } and, wait < <(jobs -p)
-   ### fix official package removal from repo problem with "NEW" code
 
 sync () {
-
- ### NEW start
 
 if	[[ -n $(checkupdates) ]]; then
 	. aurt-info --syncprint7
 	exit
 fi
-
- ### NEW end
 	
 	rm /tmp/pid   2>/dev/null
 	rm /tmp/jobs1 2>/dev/null
@@ -177,16 +169,9 @@ if 	[[ -e /tmp/updates ]]; then
 fi
 							# Create list AUR packages to check.
 
- ### NEW start
-
-# dlist=$(pacman -Qq|aursift 2>/dev/null)
 	  pacman -Qq|aursift 2>/dev/null | sort >/tmp/dlist
 
- ### NEW end
-
 	. aurt-info --syncprint2
-
- ### NEW start
 
 	pacman -Qmq|sort >/tmp/LocPkgs
 
@@ -200,7 +185,6 @@ dlist=$(comm -23 /tmp/dlist /tmp/LocPkgs)
 dlist=$(pacman -Qq|aursift 2>/dev/null)
 
 fi
- ### NEW end
 
 for P in $dlist
 do							# Prepare to check installed version -vs- available version
@@ -319,9 +303,9 @@ dependencies () {
 	if [[ -z ${uaur[*]} ]]; then unset uaur; fi
 		   								# Filter to get unmet OFFICIAL.
 		   								# uoff  =   unmet official repos
-	readarray -t uoff <<< "$(comm -23 <(echo "${uall[@]}"|fmt -1|sort\
-				|awk '{$1=$1}1') <(echo "${uaur[@]}"|fmt -1\
-				|sort|awk '{$1=$1}1'))"
+
+	readarray -t uoff <<< "$(comm -23 <(echo "${uall[@]}"|fmt -1|sort|awk '{$1=$1}1') \
+					  <(echo "${uaur[@]}"|fmt -1|sort|awk '{$1=$1}1'))"
 
 	if [[ -z ${uoff[*]} ]]; then unset uoff; fi
 
@@ -349,20 +333,16 @@ pkginfo () {
 			done
 		}
    # ---------------------------------------------------------------------------------------# IS THE PACKAGE AVAILABLE ?
-   
-### pacman -Ssq ^"${2}"$ &>/dev/null  exit codes 0 . Should exit code 1 on 'xorg' which is not a package.
-### Pacman regex broken or me?  Switched to: expac %n -S "${2}" >/dev/null on Nov 25, 2018
 
-	expac %n -S "${2}" >/dev/null || cower -i "${2}" &>/dev/null || pacman -Qi "${2}" &>/dev/null || { 
-	. aurt-info --pkginfoprint1 "${2}"
-	exit; }
+	expac %n -S "${2}" >/dev/null || aursearch -F "${2}" &>/dev/null || { . aurt-info --pkginfoprint1 "${2}"; exit ; }
+
    # --------------------------------------------------------------------------------------# IT IS INSTALLED, WANT INFO ?
 if	[[ $(pacman -Qq "${2}" 2>/dev/null | aursift 2>/dev/null) = "${2}" ]]; then
 
 	. aurt-info --pkginfoprint2 "${2}"
 
 	addinfo
-	pacman -Sii "${2}" 2>/dev/null || cower -i "${2}" || pacman -Qi "${2}"
+	auracle info "${2}" || pacman -Sii "${2}" 2>/dev/null || pacman -Qi "${2}"
 
 	exit
 fi
@@ -378,20 +358,20 @@ fi
    # ----------------------------------------------------------------------------------------# IS NOT INSTALLED, WANT INFO ?
 
 if	[[ $(pacman -Ssq "${2}" 2>/dev/null | aursift 2>/dev/null |awk '/^'"${2}"'$/') = "${2}" ]] &&
-	[[ $(cower -sq "${2}" |awk '/^'"${2}"'$/') = "${2}" ]]; then
+	[[ $(auracle search --quiet ^"${2}"$) = "${2}" ]]; then
 
 	. aurt-info --pkginfoprint5 "${2}"
 
 	addinfo
-	pacman -Sii --color=always "${2}" ; exit
+	auracle info "${2}" ; exit
 fi
 if	[[ -z $(pacman -Ssq "${2}" 2>/dev/null | aursift 2>/dev/null |awk '/^'"${2}"'$/') ]] &&
-	[[ $(cower -sq "${2}" |awk '/^'"${2}"'$/') = "${2}" ]]; then
+	[[ $(auracle search --quiet ^"${2}"$) = "${2}" ]]; then
 
 	. aurt-info --pkginfoprint5 "${2}"
 
 	addinfo
-	cower -i "${2}"; exit
+	auracle info "${2}"; exit
 fi
 if	[[ $(pacman -Ssq "${2}" 2>/dev/null |awk '/^'"${2}"'$/') = "${2}" ]]; then
 
@@ -415,7 +395,7 @@ packagelist () {
 	pacman -Q --color=always "${pkglst[@]}" | column -t
 
 	. aurt-info --packagelistprint3
-	pacman -Sl aur | column -t
+	pacman -Sl aur | awk '{ $1="" ; print }' | column -t
 	echo
 }
    #=================================================== MAKEDEPZ ======================================================
@@ -424,8 +404,10 @@ packagelist () {
 makedepz () {
 
 	. aurt-info --makedepz1
-	cower -i --format=%M --listdelim=' ' $(pacman -Qq | aursift 2>/dev/null) | \
-	fmt -1 | awk -F'<|>|=' '{print $1}' | awk '!seen[$0]++' | sort >/tmp/mdz
+
+	auracle info -F '{makedepends}' $(pacman -Qq | aursift 2>/dev/null) | \
+	fmt -1 | awk -F'<|>|=' '{print $1}' | awk '!seen[$0]++' | awk 'NF' | sort >/tmp/mdz
+
 	cat /tmp/mdz
 
 	. aurt-info --makedepz2
@@ -451,7 +433,6 @@ bysize () {
 
 	. aurt-info --bysizeprint
 	expac -H M '%m\t%n' | sort -hr | head -n 30 | column -t -R1 ; echo
-#	expac --timefmt='%F %T' '%l %n' | sort -r | head -n 30 | column -t ### by date
 }
    #===================================================== PGPKEY ========================================================
 
@@ -487,7 +468,7 @@ while	:; do
 	-lf|--lfiles)		echo ; pacman -Ql	"${2}" |awk '{print $2}'; echo			;;
 	-lm|--mdeps)		makedepz								;;
 	-lo|--lorphans)		orph									;;
-	-lv|--lvcs)			dev								;;
+	-lv|--lvcs)		dev									;;
        -pgp|key)         	pgpkey			"${@}"						;;
        -log|--paclog)		paclog									;;
        -T30|--bysize)		bysize									;;
@@ -500,6 +481,4 @@ done
 
 unset PAGER
 unset AURDEST
-	
-		### Do nothing command below to satisfy shellcheck SC2034. These vars are used in aurt-info
-	if [[ "$uaurp"||"$uoffp"||"$aurdp"||"$muallp"||"$audN"||"$nwrN"||"$equN"||"$udlist" != 0 ]]; then : ; fi 
+
